version: 2

sources:
  - name: gz_raw_data  
    database: ringed-valor-446817-a0
    schema: gz_raw_data  
    tables:
      - name: sales
        identifier: raw_gz_sales

      - name: product
        identifier: raw_gz_product
        
      - name: ship
        identifier: raw_gz_ship
        

