version: 2

sources:
  - name: gz_raw_data  
    database: ringed-valor-446817-a0
    schema: gz_raw_data  
    tables:
      - name: raw_gz_sales,
        alias: sales
      - name: raw_gz_product
        alias: product
      - name: raw_gz_ship
        alias: ship

